# -*- coding: utf-8 -*-
"""
Automated API Test Script for East Carbon Login API
Generated by generate_testcases.py
Run: pytest output/test_api_auto.py -v
"""

import pytest
import requests
import json
from urllib.parse import urljoin


# API Configuration
API_CONFIG = {
    "module": "Login",
    "endpoint": "east_carbon/login",
    "method": "POST",
    "base_url": "https://whhnhy.com:38868",
    "description": "East Carbon Login API",
    "headers": {"Content-Type": "application/json"},
    "valid_credentials": {
        "loginType": 100,
        "userType": 1,
        "username": "19900000001",
        "password": "a123456"
    }
}


class APIClient:
    """HTTP Client for API testing"""

    def __init__(self, base_url=API_CONFIG["base_url"], verify_ssl=False):
        self.base_url = base_url
        self.session = requests.Session()
        self.verify_ssl = verify_ssl

    def request(self, method, endpoint, headers=None, params=None, **kwargs):
        """Send HTTP request"""
        url = urljoin(self.base_url, endpoint)
        request_headers = {}
        if headers:
            request_headers.update(headers)

        # Disable SSL warnings
        if not self.verify_ssl:
            import urllib3
            urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

        try:
            if method.upper() == "GET":
                response = self.session.get(
                    url,
                    headers=request_headers,
                    params=params,
                    verify=self.verify_ssl,
                    **kwargs
                )
            elif method.upper() == "POST":
                response = self.session.post(
                    url,
                    headers=request_headers,
                    json=params,
                    verify=self.verify_ssl,
                    **kwargs
                )
            elif method.upper() == "PUT":
                response = self.session.put(
                    url,
                    headers=request_headers,
                    json=params,
                    verify=self.verify_ssl,
                    **kwargs
                )
            elif method.upper() == "DELETE":
                response = self.session.delete(
                    url,
                    headers=request_headers,
                    json=params,
                    verify=self.verify_ssl,
                    **kwargs
                )
            else:
                raise ValueError(f"Unsupported HTTP method: {method}")

            return response

        except requests.exceptions.SSLError:
            raise
        except requests.exceptions.ConnectionError as e:
            raise
        except requests.exceptions.Timeout as e:
            raise
        except requests.exceptions.RequestException as e:
            raise


# Test Data Generation Helper
def get_request_data(title):
    """Generate request data based on test case title"""
    valid = API_CONFIG["valid_credentials"]

    if "Normal login" in title or "Happy path" in title:
        return valid.copy()

    elif "Missing loginType" in title:
        return {"userType": valid["userType"], "username": valid["username"], "password": valid["password"]}

    elif "Missing userType" in title:
        return {"loginType": valid["loginType"], "username": valid["username"], "password": valid["password"]}

    elif "Missing username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "password": valid["password"]}

    elif "Missing password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"]}

    elif "Invalid loginType" in title:
        return {"loginType": 999, "userType": valid["userType"], "username": valid["username"], "password": valid["password"]}

    elif "Invalid userType" in title:
        return {"loginType": valid["loginType"], "userType": 99, "username": valid["username"], "password": valid["password"]}

    elif "Non-existent username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "99999999999", "password": valid["password"]}

    elif "Wrong password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": "wrongpassword"}

    elif "Empty username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "", "password": valid["password"]}

    elif "Empty password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": ""}

    elif "Null username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": None, "password": valid["password"]}

    elif "Null password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": None}

    elif "long username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "199000000011990000000119900000001199000000011990000000119900000001", "password": valid["password"]}

    elif "long password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": "a123456a123456a123456a123456a123456a123456a123456a123456a123456a123456"}

    elif "Special characters" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "user@#$%^&*()", "password": valid["password"]}

    elif "loginType as string" in title:
        return {"loginType": "100", "userType": valid["userType"], "username": valid["username"], "password": valid["password"]}

    elif "userType as string" in title:
        return {"loginType": valid["loginType"], "userType": "1", "username": valid["username"], "password": valid["password"]}

    elif "username as number" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": 19900000001, "password": valid["password"]}

    elif "password as number" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": 123456}

    elif "SQL injection in username" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "admin' OR '1'='1", "password": valid["password"]}

    elif "XSS" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": "<script>alert('XSS')</script>", "password": valid["password"]}

    elif "SQL injection in password" in title:
        return {"loginType": valid["loginType"], "userType": valid["userType"], "username": valid["username"], "password": "pass' OR '1'='1"}

    else:
        return valid.copy()


def get_request_headers(title):
    """Generate request headers based on test case title"""
    if "Missing Content-Type" in title:
        return {}
    elif "Wrong Content-Type" in title:
        return {"Content-Type": "application/xml"}
    else:
        return {"Content-Type": "application/json"}


# ============================================================================
# P0 Test Cases - Happy Path
# ============================================================================

@pytest.mark.p0
def test_tc001_normal_login():
    """TC001: Normal login with all valid parameters"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Normal login with all valid parameters")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    # Assertions
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"

    resp_json = response.json()
    assert "code" in resp_json, "Response missing 'code' field"
    assert resp_json["code"] == 200, f"Expected code 200, got {resp_json.get('code')}"

    assert "data" in resp_json, "Response missing 'data' field"
    data = resp_json["data"]
    assert "userId" in data, "Response data missing 'userId'"
    assert "accessToken" in data, "Response data missing 'accessToken'"
    assert "refreshToken" in data, "Response data missing 'refreshToken'"
    assert "expiresTime" in data, "Response data missing 'expiresTime'"

    print(f"Login successful! UserId: {data['userId']}")


@pytest.mark.p0
def test_tc002_missing_loginType():
    """TC002: Missing loginType parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Missing loginType parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with missing loginType"


@pytest.mark.p0
def test_tc003_missing_userType():
    """TC003: Missing userType parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Missing userType parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with missing userType"


@pytest.mark.p0
def test_tc004_missing_username():
    """TC004: Missing username parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Missing username parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with missing username"


@pytest.mark.p0
def test_tc005_missing_password():
    """TC005: Missing password parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Missing password parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with missing password"


@pytest.mark.p0
def test_tc006_invalid_loginType():
    """TC006: Invalid loginType parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Invalid loginType parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with invalid loginType"


@pytest.mark.p0
def test_tc007_invalid_userType():
    """TC007: Invalid userType parameter"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Invalid userType parameter")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with invalid userType"


@pytest.mark.p0
def test_tc008_nonexistent_username():
    """TC008: Non-existent username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Non-existent username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with non-existent username"
    assert resp_json["code"] in [401, 400], f"Expected 401 or 400, got {resp_json['code']}"


@pytest.mark.p0
def test_tc009_wrong_password():
    """TC009: Wrong password"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Wrong password")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with wrong password"
    assert resp_json["code"] in [401, 400], f"Expected 401 or 400, got {resp_json['code']}"


# ============================================================================
# P1 Test Cases - Authentication
# ============================================================================

@pytest.mark.p1
def test_tc010_empty_username():
    """TC010: Empty username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Empty username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with empty username"


@pytest.mark.p1
def test_tc011_empty_password():
    """TC011: Empty password"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Empty password")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with empty password"


@pytest.mark.p1
def test_tc012_null_username():
    """TC012: Null username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Null username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with null username"


@pytest.mark.p1
def test_tc013_null_password():
    """TC013: Null password"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Null password")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with null password"


# ============================================================================
# P1 Test Cases - Boundary Tests
# ============================================================================

@pytest.mark.p1
def test_tc014_long_username():
    """TC014: Extremely long username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("long username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    # Should either accept or reject, but handle gracefully
    assert "code" in resp_json


@pytest.mark.p1
def test_tc015_long_password():
    """TC015: Extremely long password"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("long password")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert "code" in resp_json


@pytest.mark.p1
def test_tc016_special_chars_username():
    """TC016: Special characters in username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("Special characters in username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert "code" in resp_json


# ============================================================================
# P1 Test Cases - Data Types
# ============================================================================

@pytest.mark.p1
def test_tc017_loginType_as_string():
    """TC017: loginType as string instead of integer"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("loginType as string")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    # May accept string numbers, may reject - depends on API
    assert "code" in resp_json


@pytest.mark.p1
def test_tc018_userType_as_string():
    """TC018: userType as string instead of integer"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("userType as string")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert "code" in resp_json


@pytest.mark.p1
def test_tc019_username_as_number():
    """TC019: username as number instead of string"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("username as number")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert "code" in resp_json


@pytest.mark.p1
def test_tc020_password_as_number():
    """TC020: password as number instead of string"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("password as number")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert "code" in resp_json


# ============================================================================
# P1 Test Cases - Format Issues
# ============================================================================

@pytest.mark.p1
def test_tc021_missing_content_type():
    """TC021: Missing Content-Type header"""
    client = APIClient(verify_ssl=False)
    headers = get_request_headers("Missing Content-Type")
    data = get_request_data("Normal login")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    # API might reject or handle anyway
    assert response.status_code in [200, 415, 400]


@pytest.mark.p1
def test_tc022_wrong_content_type():
    """TC022: Wrong Content-Type header"""
    client = APIClient(verify_ssl=False)
    headers = get_request_headers("Wrong Content-Type")
    data = get_request_data("Normal login")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code in [200, 415, 400]


@pytest.mark.p1
def test_tc023_empty_request_body():
    """TC023: Empty request body"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = {}

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    assert resp_json["code"] != 200, "Should fail with empty body"


# ============================================================================
# P2 Test Cases - Security
# ============================================================================

@pytest.mark.p2
@pytest.mark.skip("Security test - manual verification recommended")
def test_tc025_sql_injection_username():
    """TC025: SQL injection in username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("SQL injection in username")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    # Should reject malicious input
    assert resp_json["code"] != 200, "Should reject SQL injection attempt"


@pytest.mark.p2
@pytest.mark.skip("Security test - manual verification recommended")
def test_tc026_xss_username():
    """TC026: XSS attack in username"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("XSS")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    # Should reject malicious input
    assert resp_json["code"] != 200, "Should reject XSS attempt"


@pytest.mark.p2
@pytest.mark.skip("Security test - manual verification recommended")
def test_tc027_sql_injection_password():
    """TC027: SQL injection in password"""
    client = APIClient(verify_ssl=False)
    headers = {"Content-Type": "application/json"}
    data = get_request_data("SQL injection in password")

    response = client.request("POST", API_CONFIG["endpoint"], headers=headers, params=data)

    assert response.status_code == 200
    resp_json = response.json()
    # Should reject malicious input
    assert resp_json["code"] != 200, "Should reject SQL injection attempt"


# ============================================================================
# Pytest Configuration
# ============================================================================

def pytest_configure(config):
    """Pytest configuration"""
    config.addinivalue_line("markers", "p0: P0 test cases - Happy path and critical tests")
    config.addinivalue_line("markers", "p1: P1 test cases - Authentication and boundary tests")
    config.addinivalue_line("markers", "p2: P2 test cases - Security tests")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
